# Generated by Django 5.2 on 2025-09-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
