# Generated by Django 5.2 on 2025-09-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_userdetails_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_item', models.CharField(max_length=100)),
                ('budget_cost', models.IntegerField()),
                ('budget_date', models.DateField(max_length=20)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.userdetails')),
            ],
        ),
    ]
