# Generated by Django 5.2 on 2025-09-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_date',
            field=models.DateField(),
        ),
    ]
